[tool.poetry]
name = "django-object-checker"
version = "1.0.1"
description = "Hello. I'm just an abstract object ğŸ“¦ and I would be very glad to have user authorization because I hate criminals ğŸ¦¹â€â™‚ï¸ like pedophiles, robbers, hackers and so on."
authors = ["Adam Å½Ãºrek <adamzurek14@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
django = "^4.0.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-flake8 = "*"
pytest-cov = "^3.0.0"
pytest-django = "^4.5.0"

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"
